# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-12 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_num_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('name',)},
        ),
    ]
